// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv0GT9hzevlA16jPpInphN7e69fKo2VZs',
    appId: '1:595290929861:web:75c13361dcdba0c4178eac',
    messagingSenderId: '595290929861',
    projectId: 'adidas-mobile-app-main',
    authDomain: 'adidas-mobile-app-main.firebaseapp.com',
    storageBucket: 'adidas-mobile-app-main.appspot.com',
    measurementId: 'G-R9WBPJ7M76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_bXKIIYFCsIwNoxRZrHzVESuqH8C9xb8',
    appId: '1:595290929861:android:b90bd700deec6a3b178eac',
    messagingSenderId: '595290929861',
    projectId: 'adidas-mobile-app-main',
    storageBucket: 'adidas-mobile-app-main.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgwxxsN1IIhunDsUnztKOlAZGaDHEI_yo',
    appId: '1:595290929861:ios:93093c7ced1f7067178eac',
    messagingSenderId: '595290929861',
    projectId: 'adidas-mobile-app-main',
    storageBucket: 'adidas-mobile-app-main.appspot.com',
    iosBundleId: 'com.example.adidasMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgwxxsN1IIhunDsUnztKOlAZGaDHEI_yo',
    appId: '1:595290929861:ios:fccaffda55620b88178eac',
    messagingSenderId: '595290929861',
    projectId: 'adidas-mobile-app-main',
    storageBucket: 'adidas-mobile-app-main.appspot.com',
    iosBundleId: 'com.example.adidasMobileApp.RunnerTests',
  );
}
